replicaCount: 1

image:
  repository: jellyfin/jellyfin
  pullPolicy: IfNotPresent
  tag: "10.11.0"

imagePullSecrets: []

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false

service:
  type: ClusterIP
  port: 8096
  targetPort: 8096
  annotations: {}

# Ingress configuration
ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: jellyfin.cluster.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}
env: []

envFrom: []

persistence:
  enabled: true
  storageClassName: "longhorn"
  accessMode: ReadWriteOnce

  config:
    enabled: true
    size: 5Gi
    mountPath: /config

  cache:
    enabled: true
    size: 5Gi
    mountPath: /cache

  media:
    enabled: false
    size: 100Gi
    mountPath: /media
    storageClassName: "nfs"

extraVolumes: []
extraVolumeMounts: []

livenessProbe:
  httpGet:
    path: /health
    port: 8096
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8096
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

startupProbe:
  httpGet:
    path: /health
    port: 8096
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 30

priorityClassName: ""
hostNetwork: false
dnsPolicy: ClusterFirst
restartPolicy: Always

