grafana:
  adminPassword: "admin"
  ingress:
    enabled: true
    ingressClassName: traefik-internal
    hosts: 
      - grafana.cluster.local

  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://grafana-loki-gateway.prometheus-system.svc.cluster.local/
      jsonData:
        timeout: 60
        maxLines: 1000
