ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik-internal

logs:
  access:
    enabled: true
    addInternals: true
    format: json

providers:
  kubernetesCRD:
    ingressClass: traefik-internal

  kubernetesIngress:
    ingressClass: traefik-internal

service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.0.140

ingressRoute:
  dashboard:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik-internal
    matchRule: Host(`traefik.cluster.local`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    services:
      - name: api@internal
        kind: TraefikService
    entryPoints:
      - web
      - websecure

