ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik-internal

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.cluster.local`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    services:
      - name: api@internal
        kind: TraefikService
    entryPoints:
      - web
      - websecure

