ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik

ports:
  web:
    forwardedHeaders:
      trustedIPs:
        - "10.42.0.0/16"
  websecure:
    forwardedHeaders:
      trustedIPs:
        - "10.42.0.0/16"

deployment:
  kind: DaemonSet

logs:
  access:
    enabled: true
    addInternals: true
    format: json

providers:
  kubernetesCRD:
    ingressClass: traefik

  kubernetesIngress:
    ingressClass: traefik

ingressRoute:
  dashboard:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    matchRule: Host(`traefik.cluster.local`)
    services:
      - name: api@internal
        kind: TraefikService
    entryPoints:
      - web
      - websecure

