ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik-prod

ports:
  web:
    forwardedHeaders:
      trustedIPs:
        - "10.42.0.0/16"
  websecure:
    forwardedHeaders:
      trustedIPs:
        - "10.42.0.0/16"

deployment:
  kind: DaemonSet

logs:
  access:
    enabled: true
    addInternals: true
    format: json

providers:
  kubernetesCRD:
    ingressClass: traefik-prod

  kubernetesIngress:
    ingressClass: traefik-prod

service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.0.141

ingressRoute:
  dashboard:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik-internal
    matchRule: Host(`traefik-prod.cluster.local`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    services:
      - name: api@internal
        kind: TraefikService
    entryPoints:
      - web
      - websecure

metrics:
  prometheus: {}
