apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-internal
  namespace: metallb-system
spec:
  addresses:
  - 10.0.0.140-10.0.0.189
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: pool
  namespace: metallb-system
spec:
  ipAddressPools:
    - pool-internal

