apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsmasq-config
  namespace: {{ .Release.Namespace }}
data:
  dnsmasq.conf: |
    server=193.17.47.1
    server=185.43.135.1
    
    address=/cluster.local/10.0.0.140
    
    log-queries
    log-facility=-
