- name: Install K3s server
  shell: |
    curl -sfL https://get.k3s.io | K3S_TOKEN={{ k3s_token }} sh -s - server \
      --node-taint "env=dev:PreferNoSchedule" \
      --disable=traefik \
      --disable=servicelb
  args:
    creates: /usr/local/bin/k3s

- name: Wait for K3s kubeconfig
  wait_for:
    path: /etc/rancher/k3s/k3s.yaml
    timeout: 60
