apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "nfs-media"
  nfs:
    path: /mnt/zfs-pool-small/smb/media
    server: 10.0.0.215

