victoria-metrics-k8s-stack:
  fullnameOverride: "vm"
  grafana:
    plugins:
      - victoriametrics-metrics-datasource
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - grafana.cluster.local
