- hosts: kube_vms
  become: true
  tasks:
    - name: "update and upgrade apt packages"
      apt:
        upgrade: true
        update_cache: true
        install_recommends: false
        autoremove: true
