- hosts:
    - kube_vms
  become: true
  tasks:
    - name: update and upgrade apt packages
      apt:
        upgrade: true
        update_cache: true
        install_recommends: false
        autoremove: true

    - name: install curl
      apt:
        name: curl
        state: latest
        update_cache: yes

    - name: install open-iscsi
      when: inventory_hostname in groups['kube_vms']
      apt:
        name: open-iscsi
        state: latest
        update_cache: yes
