apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MrkMrk00/homelab
    targetRevision: HEAD
    path: charts/jellyfin
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
