apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  source:
    repoURL: https://github.com/MrkMrk00/homelab
    targetRevision: HEAD
    path: charts/jellyfin
    helm:
      parameters:
        - name: ingress.enabled
          value: true
        - name: ingress.className
          value: traefik-internal
        - name: persistence.storageClassName
          value: longhorn

        - name: persistence.media.enabled
          value: true
        - name: persistence.media.accessMode
          value: ReadOnlyMany
        - name: persistence.media.storageClassName
          value: nfs-media
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin

