apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    atomated:
      selfHeal: true
      prune: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-system
  source:
    repoURL: https://charts.signoz.io
    targetRevision: 0.79.0
    chart: signoz
    helm:
      valuesObject:
        signoz:
          ingress:
            enabled: true
            className: traefik
            hosts:
              - host: "signoz.cluster.local"
                paths:
                  - path: /
                    pathType: ImplementationSpecific
                    port: 8080
