kube_vms:
  children:
    k3s_server:
      hosts:
        k3s_server_0:
          ansible_host: 10.0.0.210
    k3s_worker:
      hosts:
        k3s_worker_0:
          ansible_host: 10.0.0.211
        k3s_worker_1:
          ansible_host: 10.0.0.212

  vars:
    k3s_version: "v1.33.5+k3s1"
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519.ansible
