k3s_cluster:
  children:
    server:
      hosts:
        10.0.0.220:
        10.0.0.221:
        10.0.0.222:
  vars:
    k3s_version: v1.35.2+k3s1
    extra_server_args: "--disable=traefik --disable=servicelb"
    api_endpoint: "10.0.0.220"
    token: "{{ k3s_token }}"
