apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.netbird.setupKeySecret }}
  labels:
    app: {{ include "cluster-gateway.name" . }}
type: Opaque
data:
  {{ .Values.netbird.setupKeySecretKey }}: {{ randAlphaNum 32 | b64enc }}
