- name: Install K3s worker
  shell: |
    curl -sfL https://get.k3s.io |                                        \
      K3S_VERSION={{ k3s_version }}                                       \
      K3S_URL=https://{{ hostvars['k3s_server_0']['ansible_host'] }}:6443 \
      K3S_TOKEN={{ k3s_token }}                                           \
      sh -s - agent
  when: (not k3s_bin.stat.exists) or (k3s_version != k3s_current_version_str)
